python3 'train_single.py' --train_path 'data/processed_graphs/eng/gat/_train' \
--eval_path 'data/processed_graphs/eng/gat/_eval' \
--test_path 'data/processed_graphs/eng/gat/_test' \
--src_vocab 'vocabs/gat/eng/_src_vocab' --tgt_vocab 'vocabs/gat/eng/train_vocab.model' \
--batch_size 32 --enc_type gat --dec_type transformer \
--model gat --vocab_size 16000 \
--emb_dim 8 --hidden_size 8 --distillation False \
--filter_size 8 --use_bias True --beam_size 5 \
--beam_alpha 0.1  --enc_layers 1 --dec_layers 1 \
--num_heads 2 --use_edges False --sentencepiece True \
--steps 30100 --eval_steps 1000 --checkpoint 5000 \
--alpha 0.2 --dropout 0.2 --sentencepiece_model bpe \
--reg_scale 0.0 --decay True --decay_steps 4000 \
--lang eng --opt reif --temp 7 --debug_mode True \
--eval 'data/processed_data/eng/eval_src' --eval_ref 'data/processed_data/eng/eval_tgt'
